services:
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME: root
      - DOCKER_INFLUXDB_INIT_PASSWORD: root
      - DOCKER_INFLUXDB_INIT_ORG: openems
      - DOCKER_INFLUXDB_INIT_BUCKET: openems
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: openems
    volumes:
      - influxData:/var/lib/influxdb
  postgres:
    image: postgres:10.0
    network_mode: host
    environment:
      POSTGRES_USER: openems
      POSTGRES_PASSWORD: openems
      POSTGRES_DB: openems
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  edge:
    network_mode: host
    depends_on:
      - backend
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    build:
      context: .
      dockerfile: EdgeRpi.Dockerfile
    ports:
      - 8080:8080 # Apache Felix Web Console
      - 8084:8084 # JSON/REST Api
      - 8085:8085 # JSON/Websocket Api
    volumes:
      - edgeData:/app/tools/docker/openems-edge/config.d
  ui:
    network_mode: host
    depends_on:
      - backend
      - edge
    build:
      context: .
      dockerfile: UiRpi.Dockerfile
    ports:
      - 4200:4200
  backend:
    network_mode: host
    depends_on:
      odoo:
        condition: service_healthy
    build:
      context: .
      dockerfile: BackendRpi.Dockerfile
    ports:
      - 8075:8075 # Backend-to-Backend JSON/REST Api
      - 8076:8076 # Backend-to-Backend JSON/Websocket Api
      - 8079:8079 # Apache Felix Web Console
      - 8081:8081 # Edge-Websocket
      - 8082:8082 # UI-Websocket
  odoo:
    network_mode: host
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8069" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    build:
      context: .
      dockerfile: OdooRpi.Dockerfile
    ports:
      - 8089:8089
      - 8069:8069
      - 8071:8071
      - 8072:8072

volumes:
  pgdata:
  edgeData:
  influxData:

